# Generated by Django 4.1.7 on 2023-03-12 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_reported_times'),
        ('game', '0008_match_rounds_played_alter_choice_chosen_count_and_more'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='reason')),
            ],
            options={
                'verbose_name': 'Report Reason',
                'verbose_name_plural': 'Report Reasons',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.admin', verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='modification date'),
        ),
        migrations.AddField(
            model_name='report',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='game.question', verbose_name='question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('S', 'submitted'), ('C', 'confirmed'), ('R', 'rejected')], default='S', max_length=15, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.player', verbose_name='reporter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='reports', to='feedback.reportreason', verbose_name='reason'),
            preserve_default=False,
        ),
    ]
