# Generated by Django 4.1.7 on 2023-03-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0002_question_is_active_alter_match_selected_categories_and_more'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeOrDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank='L', choices=[('L', 'like'), ('D', 'dislike')], max_length=2, verbose_name='type')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_dislike', to='game.question', verbose_name='question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like_dislike', to='accounts.player', verbose_name='like / dislike')),
            ],
            options={
                'verbose_name': 'Like Or Dislike',
                'verbose_name_plural': 'Likes Or Dislikes',
            },
        ),
    ]
