# Generated by Django 4.1.7 on 2023-03-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='reported_times',
            field=models.IntegerField(default=0, verbose_name='reported times'),
        ),
    ]
