# Generated by Django 4.1.7 on 2023-03-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='category')),
                ('is_active', models.BooleanField(verbose_name='is active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question text')),
                ('answered_count', models.IntegerField(default=0, verbose_name='answered count')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('confirmed_at', models.DateField(auto_now_add=True, null=True, verbose_name='confirmation date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.category', verbose_name='category')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='accounts.admin', verbose_name='confirmation date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='accounts.player', verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_player_score', models.IntegerField(default=0, verbose_name='starter player score')),
                ('joining_player_score', models.IntegerField(default=0, verbose_name='joining player score')),
                ('status', models.CharField(choices=[('MM', 'matchmaking'), ('OG', 'ongoing'), ('F', 'finished')], max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modificated_at', models.DateTimeField(default=models.DateTimeField(auto_now_add=True, verbose_name='creation time'), verbose_name='last modification')),
                ('turn', models.CharField(choices=[('S', 'starter'), ('J', 'joiner')], default='S', max_length=10, verbose_name='turn')),
                ('expires_at', models.DateTimeField(verbose_name='expected expiring date')),
                ('joining_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_matches_as_joiner', to='accounts.player', verbose_name='joining player')),
                ('starter_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_matches_as_starter', to='accounts.player', verbose_name='starter player')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='choice text')),
                ('chosen_count', models.IntegerField(default=0, verbose_name='chosen count')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
    ]
