# Generated by Django 4.1.7 on 2023-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, to='game.category', verbose_name='selected categories'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('MM', 'matchmaking'), ('OG', 'ongoing'), ('F', 'finished'), ('Q', 'quited')], max_length=15, verbose_name='status'),
        ),
    ]
