# Generated by Django 4.1.7 on 2023-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expected expiring date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, to='game.category', verbose_name='selected categories'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('MM', 'matchmaking'), ('OG', 'ongoing'), ('F', 'finished'), ('Q', 'quited')], max_length=15, verbose_name='status'),
        ),
    ]
