# Generated by Django 4.1.7 on 2023-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='modificated_at',
            field=models.DateTimeField(verbose_name='last modification'),
        ),
    ]
