# Generated by Django 4.1.7 on 2023-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_match_modificated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='modificated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last modification'),
        ),
    ]
