# Generated by Django 4.1.7 on 2023-03-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0004_alter_match_options_playeranswers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerAnswers',
            new_name='PlayerAnswer',
        ),
        migrations.AddField(
            model_name='match',
            name='selected_categories',
            field=models.ManyToManyField(to='game.category', verbose_name='selected categories'),
        ),
        migrations.AlterField(
            model_name='question',
            name='confirmed_at',
            field=models.DateField(blank=True, null=True, verbose_name='confirmation date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='accounts.admin', verbose_name='confirmer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='accounts.player', verbose_name='creator'),
        ),
    ]
