# Generated by Django 4.1.7 on 2023-03-12 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_modificated_at_match_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rounds_played',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)], verbose_name='round_played'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='chosen_count',
            field=models.PositiveIntegerField(default=0, verbose_name='chosen count'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='answered count'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='dislikes'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='likes'),
        ),
    ]
